# Exercise: 10-03 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web02-pod
  namespace: app02-ns
spec:
  containers:
  - name: web-app
    image: nginx:1.27.5-alpine
    ports:
    - containerPort: 80
    resources: {}
