# Exercise 23-02 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: fin01-pod
  namespace: devfin-ns
spec:
  serviceAccountName: fin01-sa
  containers:
  - image: shamimice03/kubectl-image  
    name: fin01-pod
    command:
    - sleep
    - "3600"
    resources: {}
