# Exercise: 21-03 v3.2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-role
  namespace: 
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: 
- apiGroups: [""]
  resources: [""]
  verbs: ["", "", ""]
- apiGroups: [""]
  resources: ["services"]
  verbs: 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 
  namespace: 
subjects:
- kind: ServiceAccount
  name: deploy-sa
  namespace: 
roleRef:
  kind: Role
  name: 
  apiGroup: rbac.authorization.k8s.io
