# Exercise: 27-02 v3.2.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ingress-nginx-admission
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2R6Q0NBVjhDQVFBd01qRWdNQjRHQTFVRUF3d1hhVzVuY21WemN5MXVaMmx1ZUMxaFpHMXBjM05wYjI0eApEakFNQmdOVkJBb01CVzVuYVc1NE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCmtucnBiTUJ2Z1lyeUM0cUJkVjJ5b1BsNUNCdHg4bVdGN0tYMklwcEc1dHM2NXNEdUg1Njl5WHlhdDF1b1ZpTjUKc0pVc0l2dy9HRzl6YmVOTFV1RUU1a0hqYlVPU0lBQ0FzNzE3bmVtWEhHb2YvUXZ0UEZMcGZJRlIrL2ZBcTlPYQp0djh2bVYyaUdJR0EvZmJPZ2JvRW5xbUQ0ZnlhN0YwTHQ4QkkvQ1ZLcXB1cUZ1MkxxVzh3MWVVQVpCMDhpSmlvCkEvaTM0bHZ0Y3RZL3lPYStzMFZqd0M3RlBUaHVQbDlkZmtRZzB2SjF5UzJLVElOQjBDbDdNNXlDNFdEbFBDOFMKL2RKWVZ2blUzNDhaT3pzQ00vYmx1UHcveVRKeElCMitteS9iT3BIWnBvcnJkb0dXUW52NVRLM3IyNHA1T3FRUQpxMXowSEVRN3FiT1E5UjVGOVlTZUF3SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCblRHMHZRCitlWUtxdlZkaTBqZzU2ZzVjRVlNY2RyZWh6WittbjJwTnR0dlRtYUl0ZGd4T1kwQXM1NlhnWUJIaU5SSHVTK0UKZkVNcW0yOWhNb0hDV09GVTR5R0tVYlFzSS9CK2RENWwrS09GYWp2U3VEMTNnVkpnKzBSRHMzS0VrVHk3MjU2UwprNHpJRFo4dEJKbnJvN1V0Mm5USTk1eW1sNnFLMjdXRUlYMVY5a3lsNlNPaTNrdCszSy84aE5hekVwMlIrb3A5Ci96NWxmTlJ3NEhQTGloZTl4U3Bmc2RvMFZLSU1HVThOd3RtcXJiOW85NkpmQkdlZUVIZUdtU1VvamcyckE2UE8KaTZhVEMwRFdsbWRUdjN3Ym1Gd1BnR0J2YU1WSk03TXpEMTdtSVpHSFd2TVdtNFZScmtrWXRMMnp2Y2U0RkhvWgp0bUNBV0l6Q2F6SDRQQWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
