apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-10-26T20:37:39Z"
  generation: 1
  labels:
    app: web01-deploy
  name: web01-deploy
  namespace: default
  resourceVersion: "102956"
  uid: dce3b557-f5ea-4633-9f2a-c835efc719d9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web01-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web01-deploy
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx:1.28-alpine
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-26T20:37:42Z"
    lastUpdateTime: "2025-10-26T20:37:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-26T20:37:39Z"
    lastUpdateTime: "2025-10-26T20:37:42Z"
    message: ReplicaSet "web01-deploy-7c8f656dc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
