# Exercise: 31-02 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: web02-deploy 
spec:
  replicas: 4
  selector:
    matchLabels:
      name: web02-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web02-pod 
    spec:
      containers:
      - image: nginx:1.14.2 
        name: web-app 
        ports:
        - protocol: TCP
          containerPort: 8080
