# Exercise 15-09 v3.2.0
#
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-pc
value: 1000000
globalDefault: false
description: "This priority class is for critical applications and should preempt lower-priority pods."
