# Exercise: 15-02 v3.3.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web02-pod
  labels:
    app: web-app
  annotations:
    description: "This sidecar container uses a JSON syntax"
spec:
  containers:
  - name: web-app
    image: nginx:1.28.3-alpine
    resources: {}

# Sidecar container
  - name: logging-sidecar
    image: busybox:1.36
    command: ['sh', '-c', "while true; do echo sync logs; sleep 20; done"]
    resources: {}
