# Exercise 20-02 v3.2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-adm-rb
  namespace: prdfin-ns
subjects:
- kind: Group
  name: ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-adm-role
  apiGroup: rbac.authorization.k8s.io
