apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-tester-deployment
  labels:
    app: probe-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-tester
  template:
    metadata:
      labels:
        app: probe-tester
    spec:
      containers:
      - name: probe-tester-container
        image: <YOUR-IMAGE-PATH> # IMPORTANT: Replace with the path to your built Go application image
        ports:
        - containerPort: 8080
        
        # Define resource requests/limits (Good practice for Kubernetes scheduling)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        # --- Liveness Probe Configuration (/healthz) ---
        # Checks if the application process is running and responsive. 
        # A failure here triggers a container restart.
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5 # Wait 5 seconds before first check
          periodSeconds: 5       # Check every 5 seconds
          timeoutSeconds: 3
          failureThreshold: 1    # Fail immediately on the first 500 error

        # --- Readiness Probe Configuration (/readyz) ---
        # Checks if the application is ready to accept traffic.
        # A failure here removes the pod from the Service endpoints.
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10 # Wait 10 seconds before first check
          periodSeconds: 10       # Check every 10 seconds
          timeoutSeconds: 5
          failureThreshold: 3     # Allow 3 consecutive failures before marking unready

---
apiVersion: v1
kind: Service
metadata:
  name: probe-tester-service
spec:
  # Use NodePort or LoadBalancer if testing externally. ClusterIP is sufficient for internal testing.
  type: LoadBalancer 
  selector:
    app: probe-tester
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

