# Exercise: 32-06 v3.2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev02-pvc
  namespace: dev-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dev-sc
  resources:
    requests:
      storage: 80Mi

