# Exercise: 30-05 v3.3.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: omar_ops
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pqQ0NBVTRDQVFBd0lURVJNQThHQTFVRUF3d0liMjFoY2w5dmNITXhEREFLQmdOVkJBb01BMjl3Y3pDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5vWUVIc1JsU29hcWYxZkpIVHVlcEc0CnA1WUhMQUJlS05talhpNjdGL3ozQlQ4SXdwTXNrUWRldmxkSERpSlZTTllreFN4OUEvVEIwTFJaRmQ2Qm42MWQKZUNMYUl2N1diRjgyMWIrWXlUSzl5T1hRRm11R0VjSG1pVDZEM1IvTG5hTWdmTUFHb2tnbHJRa0tuZUN1aXljTApNeU1rZVgrZzNWSFBoaXliLzNqTzBvQkdtay9IVW1oK2xvZVVQcmpSbEJ6Uk45SDFsa2s5TnpMWWpqZGZtL3psCnowbCtodnlYd3hncnNQVU9nc3JYZk5KMFIwNmxBQy8yVEZ3dWRVai9uWGNRZ3VwQTFESTEwUE9oK1BYSVpNZDcKNXRxVlo5dUZteC9xRFFRbmJWbnVEakhIeHJQa3VZb29LWjhnWG1Kb1RtQklZdjdEN2crNitWLzhWb0E4WUhrQwpBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXZwRWptZ1daK3d6c29mVlJWbzRtMzlucnFkUkpoCitsYkJ2VS9jc2hLVzNzMVlYMlcwMFhPMWt5Z0xXV1lNVWdaamx1RGRibm9ldCs3aTF5SXM1dEd3V3NYMEZVM0QKdmNLRWkxOXFhZWd5TEEwSW8yTFkweG5DVXkrWkdXZXhzT1ZVOWtTRmJ6THpUY0VWN2JWYnlmd1BxRXdDZlRPSwozb1ZveU9FQkhRSFEvZGdzZ2QyenRnTEl2endRTGZTT20vay84ZG1xKzFpOGpjVGNGMWp2MUloVU9KaTVuSyszCkZJYlZ3SU0xMFVtcGNPVEoxZG9WUTFzV3R4WXZBaFN4SzZNSStBRjJFejVQc0xSNGxjamE5a1ovQlA5eEZ4S3EKMUZHUFVsdVR3WUdhaTIxK284QTZvdDU4T09BUnBySWxGelhEU1VjcS9uSEJqcXVTTEMxOHIwd0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
