# Exercise 34-03 v3.2.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  type: ClusterIP
  selector:
    name: web-check-pod 
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80
