# Exercise 17-03 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app01-pod 
  template:
    metadata:
      labels:
        pod: app01-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        volumeMounts:
          - name: app01-vol
            mountPath: /etc/config
            readOnly: true
        command: ["/bin/sh", "-c", "printenv  && sleep 3600"] 
        resources: {}
      volumes:
        - name: app01-vol
          configMap:
            name: app01-cm
