# Exercise 17-03 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app02-pod 
  template:
    metadata:
      labels:
        pod: app02-pod 
    spec:
      containers:
        - name: app-app 
          image: busybox:1.28
          volumeMounts:
            - name: app02-vol
              mountPath: /etc/config
              readOnly: true
          command: ["/bin/sh", "-c", "printenv  && sleep 3600"] 
          resources: {}
      volumes:
        - name: app02-vol
          configMap:
            name: app02-cm
