# Exercise 25-02 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03-deploy 
  labels:
    app: store-app 
spec:
  replicas: 1  
  selector:
    matchLabels:
      pod: app03-pod 
  template:
    metadata:
      labels:
        pod: app03-pod 
    spec:
      securityContext:
        runAsUser: 1012
      containers:
      - name: busy-app 
        image: busybox:1.37.0
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 
        securityContext:
          runAsUser: 1024
        resources: {}
      - name: sidecar
        image: ubuntu
        command: [ "sleep", "3600" ]
        securityContext:
         runAsUser: 1036 
        resources: {}
