apiVersion: v1
kind: Pod
metadata:
  name: my01-pod 
spec:
  containers:
  - name: my-app 
    image: busybox:1.28
    command:
    - sh
    - -c
    - echo "The app is running! && sleep 3600"
  - name: init-service
    image: busybox:1.37.0
    command:
    - sh
    - -c
    - sleep "20";
