apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test 
spec:
  template:
    spec:
      containers:
      - name: k6-runner
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/k8s-cpu-stressor-stress.js"]
        args:
          - "-cpu=0.2"
          - "-duration=10s"
          - "-forever"
        resources:
          # Request and limit are important for a CPU-intensive test.
          # The high limit ensures the container is not throttled.
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "512Mi"
        volumeMounts:
        - name: k8s-cpu-stressor-vol 
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: k8s-cpu-stressor-vol 
        configMap:
          name: k8s-cpu-stressor 
  backoffLimit: 4

