# Exercise 16-06 v3.2.0
#
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota 
spec:
  hard:
    requests.cpu: "1" 
    requests.memory: 1Gi 
    limits.cpu: "2"
    limits.memory: 2Gi

