# Exercise 11-06 v3.2.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: web04-svc 
  namespace: default
  labels:
    bu: ops
    env: prod
    tier: frontend
spec:
  selector:
    name: web04-pod
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
