# Exercise 28-03 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app01-pod 
  namespace: prd-ns 
  labels:
    tier: frontend
    env: prd
spec:
  containers:
    - name: frontend
      image: nginx:latest 
      imagePullPolicy: Always 
      ports:
         - containerPort: 80
      resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prd-ns
  labels:
    tier: frontend
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
