# Exercise 28-03 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web01-pod
  namespace: dev-ns
  labels:
    tier: backend
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.21-alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web01-svc
  namespace: dev-ns
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    pod: web01-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
