# Exercise 33-02 v3.2.0
#
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-cpu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-cpu-deploy
  minReplicas: 1
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # Sets the cooldown period to 30 seconds (1/2 minute)
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30
