# Exercise 44-02 v3.2.0
#
---
# Job Runner for CPU
apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test-cpu-job # CHANGED: Job name reflects CPU test
spec:
  template:
    spec:
      containers:
      - name: k6-app
        image: grafana/k6:latest # Official K6 image
        command: ["k6", "run", "/k6/stress_test_cpu.js"] # Command runs the CPU script
        volumeMounts:
        - name: k6-script
          mountPath: /k6
      restartPolicy: Never
      volumes:
      - name: k6-script
        configMap:
          name: stress-test-cpu-cm # References the CPU ConfigMap
