# Exercise 23-03 v3.2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-role
  namespace: 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["", "", ""]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 
  namespace: 
subjects:
- kind: ServiceAccount
  name: 
  namespace: 
roleRef:
  kind: Role
  name: 
  apiGroup: rbac.authorization.k8s.io
