# Exercise 32-03 v3.2.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db01-cm 
  namespace: db-ns
  labels:
    app: db01-db
data:
  POSTGRES_DB: db01-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: BadPass@1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01-deploy
  namespace: db-ns
  labels:
    app: db01-db
spec:
  selector:
    matchLabels:
      pod: db01-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: db01-pod
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db01-cm 
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db01-svc
  namespace: db-ns
  labels:
    app: db01-db
spec:
  selector:
    pod: db01-pod
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
