# Exercise 32-03 v3.2.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db02-cm 
  namespace: db-ns
  labels:
    app: db02-db
data:
  POSTGRES_DB: db02-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: BadPass@1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db02-deploy
  namespace: db-ns
  labels:
    app: db02-db
spec:
  selector:
    matchLabels:
      pod: db02-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: db02-pod
    spec:
      tolerations:
        - key: "tier"
          operator: "Equal"
          value: "db"
          effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db02-cm 
          volumeMounts:
            - name: db02-vol
              mountPath: /var/lib/postgresql/data
          resources: {}
      volumes:
        - name: db02-vol
          hostPath:
            path: /tmp/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: db02-svc
  namespace: db-ns
  labels:
    app: db02-db
spec:
  selector:
    pod: db02-pod
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
