# Exercise 27-02 v3.2.0
#
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
type: Opaque
data:
  ca: <Insert ca.crt secret here>
  cert: <Insert ingress-nginx-admission crt here> 
  key: <Insert ingress-nginx-adminission key here>

