# Exercise: 30-05 v3.3.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dana_dev
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pqQ0NBVTRDQVFBd0lURVJNQThHQTFVRUF3d0laR0Z1WVY5a1pYWXhEREFLQmdOVkJBb01BMlJsZGpDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU0rLzhrQ20rTjNoN3B3eW5USDNDZzV3CnFIY2M0c1lFanNXeklSZHBKcC9FY1IxOXEwWmFTbktZWXhRSmRSM05TeVpyVFl1U05OZ1hySmF3ajMrSHE0bVIKbVBYWFBKUWJGRU1FdUFkeVRjdHNjbFFENE5kbWkyUFYrUUVjT0taVldNdWR0Q2NlQjJqNXdFNVhReHRGTjRodgpIdWVxM1daTnczS2lDOENzZmJxWW1DYU8veUZQdjEzREtscWhLQ21IOGpFZVZRYW5mcXY0RW1WbURLZ1BjdUJZCkxtV1g3WFg4NUpqYkpMcmMyRGFrYWFoR1VkNjVUWGFFOWNuN2laRnNnbVBjMG45elRSSlU0L0tqUjlUdEtQeHQKT3RyNm1OZ1BQNzRQei9DZ2hEUUZlOHVpYURCMHpNRDhvS20wQ0NFR3ZzZHI0R0dRK3Rva1JrWmlBakp2SmdFQwpBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUw4Wm8xOEdJcjBYYnFCMk5rUmZxSWdSbU9QaXRZCm1TSUNQQnhxMTg3VEFMZXdoaVM2cFFGWENqSmtCWUk2RnE1U0RocVZxeTJ6MjgwcWFQZTE3R2VTSDdhcUx3WUEKbHpBOTNFVTgwU3piN1ZlZXpxTzVlaytPQmJXME41c0l3dmY3aU1UUFV3aHdpZlA2WlFIWlhFUzJBdzJPeHAyOAp4aTk2ankvWUxidEVNUEFGVy9hVm1GcEU0bDNiU0dMSWdtWDkrZWcrZWFiWk1iQkdsNXhsTEh1TlE4OGlLZnlMCnRtVG05VUNyR2tHWjluM0tJUVFCWjUrekFaSE5FblJYMXBTOCtwb25rNnFxcDhEWDJvT1dTTVdzSWpRSC9wb2YKVzlOTWhUUk1FdENnVjRleGZPd3gzVXBLbTAyalBPM3V5dVdUYkdTRE9PdXV5MVlXb1Znd2YwMHoKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
