# Exercise: 35-02 v3.3.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ingress-nginx-admission
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2R6Q0NBVjhDQVFBd01qRWdNQjRHQTFVRUF3d1hhVzVuY21WemN5MXVaMmx1ZUMxaFpHMXBjM05wYjI0eApEakFNQmdOVkJBb01CVzVuYVc1NE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCm9UaENoZFh1RGdJNnU0R1FuaHNpZk0wVkFUYXpJdGxvclIzVndkVmJtWGZ1OStKUmREV3hsVjlmTEtlbjVaTnMKMTE5WDAybFYya25IdUtNRndEREdpSlNxeThpR0RFZEkybEovQ2hBSWU3WFI5d04wZlkvSTc5azJtZXZiOG4rdgpUeGl1aG12SUFtQU9NTUtNM2U5N0p0b0JVYWhhTmdybTlESjFWd2FrWVZOcUdkaDU1a2ttVXFiYWJ1RzI2QkowCnY4U1Z3bFROMG9sU2dVaVZZamZDcElNSzhFSGpHOTBjTzZYZDhQNHNBSzVuRStlQXltNUJwQUd5YnBod1JmNWMKZ3IycS9ZSVpidmVXajlQYVN3OHloMXJ1UVlBRHhCR0EzREc3T2pndnNMU2xaTUpIeGdyQ1RJTXdtVmRnbllOUgpuTzhYWldhUjBUa3BiUlM5NTZlSHp3SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIRlYybHcvCnozdjBJaU1jRXVRSUNROXpWZ3hBNktTWFdQM1hneHJEaHBUcDgxUlNIMlZlZERqM1ZBWEFVNDU4L0tNWnBTL0IKQ3R4bXU5aXNOaExxLzFxNm1BMWxaZDltaWdMQy9rc2E3NFdXdUpMdTJ3UjVKTnlrTHpkc3hQblhQckFXVmVWOQpZQ1pDTTZZc2hDUVN6ZjRiZDRueXdNazlGRVovdGhMbmdCTWxLaHBIM0V0dEExYzluWmhGaHdpWURKWklLcTY1CkZ6cFRoQUIyazc0UXpWYlFhZXNIcXNkNVNDN09UVCtHQlNlV3RSR3RVZHpORE9GcTlHZnBzdjJlNjVHbU1TMHcKNUd0cWNhNXdiditHcjN3eFUwWkNBNFFvZWRFdVNsbUhYanNsM25zYmpLa25zUzF2SzdoVGZ1c0JXZ3BEVzljZQpvb0UwSzU2U2k4QzNpL2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
