# Exercise 03-02 v3.2.0
#
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: edu
# These attributes prevent the install of Kind CNI
# The Pod and Service subnets are Calico defaults
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
        node-labels: "ingress-ready=true"
  extraPortMappings:
# Ports configured for Kubernetes Dashboard
  - containerPort: 30443
    hostPort: 8443
    listenAddress: "127.0.0.1"
    protocol: TCP
# Commonly used ports for Ingress Controller
#  - containerPort: 80
#    hostPort: 80
#    listenAddress: "0.0.0.0"
#    protocol: TCP
#  - containerPort: 443
#    hostPort: 443
#    listenAddress: "0.0.0.0"
#    protocol: TCP
# These attributes set the localhost port to
# map to a Service port.
- role: worker
# These attributes set the nodes memory size
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
