# Exercise 03-02 v3.2.0
#
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: edu
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=4Gi"
  labels:
    ingress-ready: "true"
# The extra port mappings are required for 
# the load balancer metalLB.
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30100
    hostPort: 30100
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30200
    hostPort: 30200
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30300
    hostPort: 30300
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=6Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=6Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=6Gi"
