# Exercise 33-02 v3.2.0
#
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hpa-load-tester 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: load-tester 
  template: 
    metadata: 
      labels: 
        app: load-tester 
    spec: 
     containers: 
       - name: load-generator 
         image: wmdailey/hpa-load-tester:latest 
         ports: 
           - containerPort: 8080 
         resources: 
           requests: 
             cpu: "250m" # 25% of one core. HPA uses this as the baseline. 
             memory: "256Mi" # 256 MiB of memory. HPA uses this as the baseline. 
           limits: 
             cpu: "1000m" # Hard limit of 1 CPU core 
             memory: "1024Mi" # Hard limit of 1 GiB memory (adjust based on your node size)
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-load-tester 
spec:
  selector:
    app: load-tester 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
