# Exercise 15-06 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web01-pod 
spec:
  containers:
  - name: web-app 
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "30Mi"
      limits:
        cpu: "600m"
        memory: "80Mi"

