# Exercise 15-04 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: mem-stress02
spec:
  containers:
    - name: mem-stress
      image: polinux/stress
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - 10M # Reduce the memory request below the limits
        - --vm-hang
        - "1"
      resources:
        requests:
          memory: 5Mi
        limits:
          memory: 15Mi
