# Exercise 29-7 v3.2.0
#
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # This is default but it can be changed
parameters:
  archiveOnDelete: "false"
