# Exercise 29-07 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: nfs-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: prd01-control-plane # set the nfs server
            - name: NFS_PATH
              value: /srv/nfs/kubedata # set nfs exports path
          resources: {}
      volumes:
        - name: nfs-client-root
          nfs:
            server: prd01-control-plane # set the nfs server
            path: /srv/nfs/kubedata # set the nfs exports path
