# Exercise 02-03 v3.2.0
#
# A basic configuration file for a KIND cluster.
# This creates a cluster with four nodes: one control plane and three workers.
# The name of the cluster is edu.
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: edu
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
