# Exercise 15-07 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app01-pod 
  template:
    metadata:
      labels:
        pod: app01-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 
        resources: {}
