# Exercise 38-03 v3.2.0
#
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # The name must be plural.group
  name: databases.db.example.com
spec:
  # Group name (must contain a dot)
  group: db.example.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - db
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Type of database (e.g., postgres, mysql)
                engine:
                  type: string
                  description: The database engine (e.g., postgres, mysql).
                # Size of the persistent volume claim (PVC)
                storageSize:
                  type: string
                  description: The size of the persistent volume claim (e.g., 10Gi).
                # Credentials secret name
                credentialsSecret:
                  type: string
                  description: The name of the Kubernetes secret holding credentials.
              required:
                - engine
                - storageSize
                - credentialsSecret
            status:
              type: object
              properties:
                # Connection information
                connectionURL:
                  type: string
                  description: The internal cluster connection URL for the database.
                deploymentState:
                  type: string
                  description: Current state (e.g., Pending, Ready, Failed).
                pvcName:
                  type: string
                  description: Name of the PersistentVolumeClaim created.
