# Exercise 29-08 v3.2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
