apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websitemirrors.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetUrl:
                  type: string
  scope: Namespaced
  names:
    plural: websitemirrors
    singular: websitemirror
    kind: WebsiteMirror
    shortNames:
      - wm
