# Exercise 22-02 v3.2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ops-adm-role
  namespace: prdfin-ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pods-role
  namespace: prdfin-ns
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
