This Kubernetes Job manifest runs a k6 load test as a one-off task.
# It uses the k6 script stored in the ConfigMap created above.

apiVersion: batch/v1
kind: Job
metadata:
  # A unique name for this job.
  name: load-test-memory 
  namespace: default
spec:
  # Defines how many times the job should be run before giving up.
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: k6-runner
        # Use a pre-built k6 image to execute the test.
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/load-test-memory.js"]
        volumeMounts:
        # Mount the ConfigMap as a volume at the specified path.
        - name: scripts-vol
          mountPath: /scripts/load-test-memory.js
          subPath: load-test-memory.js
      volumes:
      - name: scripts-vol
        configMap:
          # The name of the ConfigMap to mount. This must match the name above.
          name: load-test-memory 
      # The pod will not be restarted if it fails.
      restartPolicy: OnFailure

