# Exercise 11-04 v1.2.0 
#
----
apiVersion: v1
kind:  Deployment
metadata:
  name: my0x-deploy
  labels:
    env: devl
spec:
  template:
    metadata:
     labels:
        env: dev
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      env: devl
