# Exercise: 13-02 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web02-pod
  labels:
    app: web-app
  annotations:
    description: "This is a web application pod with a sidecar container and a command using JSON syntax"
spec:
  containers:
  - name: web-app
    image: nginx:1.24
    resources: {}

# Sidecar container
  - name: logging-sidecar
    image: busybox:1.28
    command: ['sh', '-c', "while true; do echo sync logs; sleep 20; done"]
    resources: {}
