apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis01-svc
  name: redis01-svc
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis01-svc
  type: ClusterIP
status:
  loadBalancer: {}
