apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-traffic-counter 
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-traffic-counter
  template:
    metadata:
      labels:
        name: web-traffic-counter
    spec:
      containers:
      - name: web-traffic-counter
        image: wmdailey/web-traffic-counter:latest
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 5000

