# Exercise 34-02 v3.2.0
#
cat <<EOF >> static-busy.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-busy
  labels:
    app: static-busy
spec:
  containers:
    - name: static-busy
      image: busybox:1.36.1
      command:
        - sleep
        - "3600"
      resources: {}
EOF
