# Exercise 38-02 v3.2.0
#
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.example.com 
spec:
  # Group name to use in the API URL: /apis/com/v1/websites
  group: example.com
  names:
    plural: websites
    singular: website
    kind: Website
    shortNames:
    - web
  scope: Namespaced

  versions:
  - name: v1
    served: true
    storage: true

    schema:
      openAPIV3Schema:
        type: object
        properties:
          # Define the Custom Resource's spec structure
          spec:
            type: object
            required:
            - domain
            - replicas
            properties:
              domain:
                description: The primary domain name for the website.
                type: string
              replicas:
                description: The desired number of website replicas (pods).
                type: integer # Replicas is correctly defined as an integer
                minimum: 1
                default: 1
