# Exercise: 27-02 v3.2.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ingress-nginx-adminission
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2VUQ0NBV0VDQVFBd05ERWlNQ0FHQTFVRUF3d1phVzVuY21WemN5MXVaMmx1ZUMxaFpHMXBibWx6YzJsdgpiakVPTUF3R0ExVUVDZ3dGYm1kcGJuZ3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRQ2pEZFBleVB1RGViVUJtN3ByQ3dtMStQT2VBR1E2UUpuVUJsR2UxNVlKYUw4K1ZMd0dHWVoybVVEQjRVdWsKaTg2RGtDUWY0ampjUG1nTFFtazY0Qkg3STdvUkN5MXU5QW52eTlkUk9MQ1BzRDRMTTdXWGY0K0QySVJaRUZOMgpSTFlEUnVYNTcvYittR1hjWlVDbG9VOWFsN3U5Mmp4Zlk4bXdqK1puRkhONXlMVTZQVXRIZ3FnMWVCQmdSQ2xkCmZIdjFmZzh5RmdpZm85eWJaNkFsakxYb0dYaHo0YWcwdFR4cm5LZHo3VzRKbHloVGNjMzFqNzFZY3g1SkxhSmkKdVcyMWlSbTh3WnVXcEJRUnNwR3UrWWd3V0EwanlvcmVrL3dLZ1N5L0tDVjZYaFVJU0V3R2tSUVZvcmdhT2Ixbgo0ZTVIa0VnU282RkVkeGVVS2JKbEN6WnRBZ01CQUFHZ0FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUMERjCkZia3QyWSs0Z3RBc1BkMncxNVkveXV6cVc4R2VPRDZzMHZEOGRkOHhwQmJYTWlDNW1WSHk1UnE5eTVkTElXejgKRzU1WkJpbUwza2xTc0MvTFBXYU9ob0Y5S2Q5Z2dXM2xKSGdZVkxDUDM5bkVlQjhvY0hNSklmTEZUYTZqWjBITAo0aE9nNW1ic205S0dKaHIwSnhLSDJYYlpzTDFiYldWVmsxNDVobXJCQ2FxYURiRVAwWnZTNHZiZmo2NGk2QTdrCi8xUDNvbEtCQ2tYL2ZPNmV5L29GcEgzUTU1R2Z4UW96SUJGSXFaNDkxTUpyN1R6TGx6b0NmeHphdnd5YWo2OFcKNTNtNVBFWmhrOE5FemcrSlVmOEEvQnp6OHNHQXM0ZGtsYURWVDR5d3NpeEsvMVNodlo0eHorOUtxNUc1YlUwTAp4VHM2STd3UFNWT2M2eENpZ2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
