# Exercise 20-04 v3.2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-sc-adm-crb
subjects:
- kind: User
  name: omar_ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pv-sc-adm-crole
  apiGroup: rbac.authorization.k8s.io
