# Exercise 16-06 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web03-pod 
spec:
  containers:
  - name: web-app 
    image: nginx
    resources:
      requests:
        cpu: "400m"
        memory: "600Mi"
      limits:
        cpu: "800m"
        memory: "800Mi"

