# Exercise: 12-02 v3.2.0
#
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: nginx-rs 
spec:
   replicas: 2
   selector:
      matchLabels:
        env: prod
        tier: frontend
   template:
     metadata:
       labels:
        tier: backend
     spec:
       containers:
       - name: nginx
         image: nginx
