# Exercise 33-02 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cpu
  template:
    metadata:
      labels:
        app: test-cpu
    spec:
      containers:
      - name: test-cpu
        image: wmdailey/k8s-test-cpu:latest 
        ports:
        - containerPort: 8080
        resources:
          # Define resource limits to see the effect of the stress on CPU.
          # The requests section ensures the pod gets a minimum amount of CPU.
          requests:
            cpu: "250m" # 25% of a core
            memory: "64Mi"
          # The limits section prevents the pod from consuming more than this amount.
          # This helps in preventing a single pod from consuming all node resources.
          limits:
            cpu: "500m" # 50% of a core
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: test-cpu 
spec:
  selector:
    app: test-cpu
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

