# Exercise 13-03 v3.2.0 
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web02-pod
  labels:
    app: web-app
  annotations:
    description: "This is a web application pod with an init container"
spec:
# Init containers
  initContainers:
    - name: init01-pod 
      image: busybox
      command:
        - sh
        - -c
        - sleep 10
    - name: init02-pod 
      image: busybox:1.28
      command:
        - sh
        - -c
        - sleep 180
    - name: init03-pod 
      image: busybox:1.28
      command:
        - sh
        - -c
        - sleep 60
  containers:
    - name: web-app
      image: nginx:1.24

