# Exercise 14-05 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web02-deploy 
  labels:
    app: store-app 
spec:
  selector:
    matchLabels:
      pod: web02-pod 
  template:
    metadata:
      labels:
        pod: web02-pod 
        app: prdfin
    spec:
      containers:
      - name: web-app
        image: nginx:latest
        resources: {}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prdfin 
            topologyKey: "kubernetes.io/hostname"
