# Exercise 14-04 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web06-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web06-pod
  template:
    metadata:
      labels:
        pod: web06-pod 
    spec:
      containers:
        - name: web-app 
          image: nginx:1.24 
          ports:
            - protocol: TCP
              containerPort: 8080
          resources: {}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
