# Exercise 14-04 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web02-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web02-pod
  template:
    metadata:
      labels:
        pod: web02-pod 
    spec:
      containers:
        - name: web-app
          image: nginx:1.24 
          ports:
            - protocol: TCP
              containerPort: 8080
          resources: {}
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
                - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
